[colors]
[[colors.indexed_colors]]
index = 16
color = "0xd18616"

[[colors.indexed_colors]]
index = 17
color = "0xff938a"

[colors.primary]
background = "0x22272e"
foreground = "0x768390"

[colors.normal]
black = "0x22272e"
red = "0xff938a"
green = "0x6bc46d"
yellow = "0xc69026"
blue = "0x6cb6ff"
magenta = "0xb083f0"
cyan = "0x56d4dd"
white = "0x768390"

[colors.bright]
black = "0x636e7b"
red = "0xff938a"
green = "0x6bc46d"
yellow = "0xdaaa3f"
blue = "0x6cb6ff"
magenta = "0xdcbdfb"
cyan = "0x56d4dd"
white = "0x768390"
