[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#ffffff"
cursor = "#ffffff"

[colors.normal]
black = "#4e4e4e"
red = "#ff6c60"
green = "#a8ff60"
yellow = "#ffffb6"
blue = "#96cbfe"
magenta = "#ff73fd"
cyan = "#c6c5fe"
white = "#eeeeee"

[colors.bright]
black = "#7c7c7c"
red = "#ffb6b0"
green = "#ceffab"
yellow = "#ffffcb"
blue = "#b5dcfe"
magenta = "#ff9cfe"
cyan = "#dfdffe"
white = "#ffffff"
