[colors.primary]
background = "#263238"
foreground = "#eeffff"

[colors.normal]
black = "#000000"
red = "#e53935"
green = "#91b859"
yellow = "#ffb62c"
blue = "#6182b8"
magenta = "#ff5370"
cyan = "#39adb5"
white = "#a0a0a0"

[colors.bright]
black = "#4e4e4e"
red = "#ff5370"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#f07178"
cyan = "#89ddff"
white = "#ffffff"
