# Name: Matrix
# Author: OK100

[colors.primary]
background = "#000000"
foreground = "#00cc00"

[colors.cursor]
text = "#000000"
cursor = "#00cc00"

[colors.normal]
black = "#000000"
red = "#55ff55"
green = "#00cc00"
yellow = "#00cc00"
blue = "#005500"
magenta = "#55ff55"
cyan = "#00cc00"
white = "#00cc00"

[colors.bright]
black = "#000000"
red = "#55ff55"
green = "#55ff55"
yellow = "#55ff55"
blue = "#005500"
magenta = "#55ff55"
cyan = "#55ff55"
white = "#00cc00"
