[colors.primary]
background = "#292d3e"
foreground = "#959dcb"
bright_foreground = "#d0d0d0"

[colors.cursor]
text = "#292d3e"
cursor = "#959dcb"

[colors.normal]
black = "#292d3e"
red = "#f07178"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#d0d0d0"

[colors.bright]
black = "#434758"
red = "#ff8b92"
green = "#ddffa7"
yellow = "#ffe585"
blue = "#9cc4ff"
magenta = "#e1acff"
cyan = "#a3f7ff"
white = "#ffffff"
