[colors.primary]
background = "#ffffff"
foreground = "#61707a"

[colors.normal]
black = "#0b141a"
red = "#ff4053"
green = "#11ab00"
yellow = "#bf8c00"
blue = "#0099ff"
magenta = "#9854ff"
cyan = "#00a5ab"
white = "#ffffff"

[colors.bright]
black = "#0b141a"
red = "#ff4053"
green = "#11ab00"
yellow = "#bf8c00"
blue = "#0099ff"
magenta = "#9854ff"
cyan = "#00a5ab"
white = "#ffffff"
