[colors.primary]
background = "#2e3436"
foreground = "#eeeeec"

[colors.normal]
black = "#2e3436"
red = "#cc0000"
green = "#73d216"
yellow = "#edd400"
blue = "#3465a4"
magenta = "#75507b"
cyan = "#f57900"
white = "#d3d7cf"

[colors.bright]
black = "#2e3436"
red = "#ef2929"
green = "#8ae234"
yellow = "#fce94f"
blue = "#729fcf"
magenta = "#ad7fa8"
cyan = "#fcaf3e"
white = "#eeeeec"
